Batch size bug
neuralmagic/yolact pull request #23
Opened 2021-11-24 23:46 UTC by rahul-tuli

* Added a progress bar for warm up iterations
* milliseconds calc

2021-11-24 23:56 UTC, bfineran commented on eval.py
> +            elif args.num_iterations and iteration > args.warm_up_iterations + args.num_iterations:
fix break condition, iterations are zero indexed
```suggestion
            elif args.num_iterations and iteration >= args.warm_up_iterations + args.num_iterations:
```

2021-11-24 23:58 UTC, bfineran requested changes
local tests looking good, two quick suggestions

2021-11-24 23:58 UTC, bfineran commented on eval.py
> +            print('Average: %5.2f fps, %5.2f ms' % (args.batch_size / frame_times.get_avg(), 1000*avg_seconds / args.batch_size))
lets report the FPS and then the latency per batch, so no need to divide by batch size
```suggestion
            print('Average: %5.2f fps, %5.2f ms per batch' % (args.batch_size / frame_times.get_avg(), 1000*avg_seconds)
```

2021-11-25 01:18 UTC, bfineran approved these changes

2021-11-29 17:26 UTC, markurtz approved these changes

2021-11-29 17:26 UTC, merged